commonLabels:
  environment: dev
  organization: IT
  applicationn: fdp
  size: S
commonAnnotations:
  scheduler.alpha.kubernetes.io/node-selector: "role=apps"
namespace: "igou_app_team"
patches:
  - patch: |-
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: not_important_name
      spec:
        hard:
          pods: 30
    target:
      name: object-quota
resources:
 - github.com/David-Igou/example-dev-namespace/example-namespace
