commonLabels:
  environment: dev
  organization: IT
  applicationn: fdp
  size: S
commonAnnotations:
  scheduler.alpha.kubernetes.io/node-selector: "role=apps"
namespace: "igou_app_team"
resources:
 - github.com/David-Igou/example-dev-namespace/example-namespace
